/********************************************************************
* Analysis_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Analysis_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAnalysis_dict();
extern void G__cpp_setup_inheritanceAnalysis_dict();
extern void G__cpp_setup_typetableAnalysis_dict();
extern void G__cpp_setup_memvarAnalysis_dict();
extern void G__cpp_setup_globalAnalysis_dict();
extern void G__cpp_setup_memfuncAnalysis_dict();
extern void G__cpp_setup_funcAnalysis_dict();
extern void G__set_cpp_environmentAnalysis_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/Analysis.h"
#include "include/Configuration.h"
#include "include/HistoManager.h"
#include "include/Hit.h"
#include "include/Processor.h"
#include "include/TreeManager.h"
#include "include/Analysis.h"
#include "include/Configuration.h"
#include "include/HistoManager.h"
#include "include/Hit.h"
#include "include/Processor.h"
#include "include/TreeManager.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Analysis_dictLN_TClass;
extern G__linked_taginfo G__Analysis_dictLN_TBuffer;
extern G__linked_taginfo G__Analysis_dictLN_TMemberInspector;
extern G__linked_taginfo G__Analysis_dictLN_TObject;
extern G__linked_taginfo G__Analysis_dictLN_TNamed;
extern G__linked_taginfo G__Analysis_dictLN_TString;
extern G__linked_taginfo G__Analysis_dictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Analysis_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Analysis_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Analysis_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Analysis_dictLN_TF1;
extern G__linked_taginfo G__Analysis_dictLN_TH1F;
extern G__linked_taginfo G__Analysis_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__Analysis_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__Analysis_dictLN_TH2F;
extern G__linked_taginfo G__Analysis_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Analysis_dictLN_TFile;
extern G__linked_taginfo G__Analysis_dictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Analysis_dictLN_Event;
extern G__linked_taginfo G__Analysis_dictLN_pairlEintcOintgR;
extern G__linked_taginfo G__Analysis_dictLN_Configuration;
extern G__linked_taginfo G__Analysis_dictLN_Processor;
extern G__linked_taginfo G__Analysis_dictLN_vectorlEHitmUcOallocatorlEHitmUgRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_reverse_iteratorlEvectorlEHitmUcOallocatorlEHitmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Analysis_dictLN_maplEintcOvectorlEfloatcOallocatorlEfloatgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Analysis_dictLN_vectorlEPacketmUcOallocatorlEPacketmUgRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_reverse_iteratorlEvectorlEPacketmUcOallocatorlEPacketmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Analysis_dictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Analysis_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__Analysis_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Analysis_dictLN_TCanvas;
extern G__linked_taginfo G__Analysis_dictLN_HistoManager;
extern G__linked_taginfo G__Analysis_dictLN_TTree;
extern G__linked_taginfo G__Analysis_dictLN_TreeManager;
extern G__linked_taginfo G__Analysis_dictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR;
extern G__linked_taginfo G__Analysis_dictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
